[logging]
"console level" = "INFO"
"file level" = "INFO"

[modules]
deliver = [
    "git",
]

[git]
directory = "hworker_personal"

[git.users]
"Кибизов Кирилл" = "https://github.com/auraxite/msu-prac-3.git"
"Александр Броничев" = "https://github.com/MagnificentSAS/MSU-repo.git"

[tasks._default]
time_limit = 2

[tasks."20250909/1"]
deliver_ID = "20250909/1"
open_date = 2025-09-09
[tasks."20250916/1"]
deliver_ID = "20250916/1"
open_date = 2025-09-16
[tasks."20250916/2"]
deliver_ID = "20250916/2"
open_date = 2025-09-16
[tasks."20250916/3"]
deliver_ID = "20250916/3"
open_date = 2025-09-16
[tasks."20250923/1"]
deliver_ID = "20250923/1"
open_date = 2025-09-23
[tasks."20250923/2"]
deliver_ID = "20250923/2"
open_date = 2025-09-23
[tasks."20250923/3"]
deliver_ID = "20250923/3"
open_date = 2025-09-23
[tasks."20250930/1"]
deliver_ID = "20250930/1"
open_date = 2025-09-30
[tasks."20250930/2"]
deliver_ID = "20250930/2"
open_date = 2025-09-30
[tasks."20250930/3"]
deliver_ID = "20250930/3"
open_date = 2025-09-30
[tasks."20251007/1"]
deliver_ID = "20251007/1"
open_date = 2025-10-07
[tasks."20251007/2"]
deliver_ID = "20251007/2"
open_date = 2026-10-07
[tasks."20251007/3"]
deliver_ID = "20251007/3"
open_date = 2026-10-07
[tasks."20251014/1"]
deliver_ID = "20251014/1"
open_date = 2025-10-14
[tasks."20251014/2"]
deliver_ID = "20251014/2"
open_date = 2025-10-14
[tasks."20251014/3"]
deliver_ID = "20251014/3"
open_date = 2025-10-14
[tasks."20251021/1"]
deliver_ID = "20251021/1"
open_date = 2025-10-21
[tasks."20251021/2"]
deliver_ID = "20251021/2"
open_date = 2025-10-21
[tasks."20251021/3"]
deliver_ID = "20251021/3"
open_date = 2025-10-21
[tasks."20251028/1"]
deliver_ID = "20251028/1"
open_date = 2025-10-28
[tasks."20251028/2"]
deliver_ID = "20251028/2"
open_date = 2025-10-28
[tasks."20251028/3"]
deliver_ID = "20251028/3"
open_date = 2025-10-28
[tasks."20251110/1"]
deliver_ID = "20251110/1"
open_date = 2025-11-10
[tasks."20251110/2"]
deliver_ID = "20251110/2"
open_date = 2025-11-10
[tasks."20251110/3"]
deliver_ID = "20251110/3"
open_date = 2025-11-10
[tasks."20251111/1"]
deliver_ID = "20251111/1"
open_date = 2025-11-11
soft_deadline_delta = "open_date+9d"
[tasks."20251111/2"]
deliver_ID = "20251111/2"
open_date = 2025-11-11
soft_deadline_delta = "open_date+9d"
[tasks."20251111/3"]
deliver_ID = "20251111/3"
open_date = 2025-11-11
soft_deadline_delta = "open_date+9d"
[tasks."20251118/1"]
deliver_ID = "20251118/1"
open_date = 2025-11-18
[tasks."20251118/2"]
deliver_ID = "20251118/2"
open_date = 2025-11-18
[tasks."20251118/3"]
soft_deadline_delta = "open_date+9d"
open_date = 2025-11-18
[tasks."20251125/1"]
deliver_ID = "20251125/1"
open_date = 2025-11-25
[tasks."20251125/2"]
deliver_ID = "20251125/2"
open_date = 2025-11-25
[tasks."20251202/1"]
deliver_ID = "20251202/1"
open_date = 2025-12-02
[tasks."20251202/2"]
deliver_ID = "20251202/2"
open_date = 2025-12-02

[score]
score_directory = "scores"

[check]
directory = "hworker_check"

[publish] 
course_name = "My prac"
SECRET_KEY = "8556aa9cfdd8c8e0884d1b2568985789372281093f338caf5cc145fdb9e5f7b5"
