[logging]
"console level" = "INFO"
"file level" = "INFO"

[modules]
deliver = [
    "git",
]

[git]
directory = "hworker_personal"

[git.users]
"Кибизов Кирилл" = "https://github.com/auraxite/msu-prac-3.git"
"Броничев Александр" = "https://github.com/MagnificentSAS/MSU-repo.git"

[imap]
host = "host"
port = 993
folder = "INBOX"
username = "username"
password = "password"
letter_limit = -1

[imap.users]

[file]
root_path = "files"

[file.users]

[tasks."20250909/1"]
deliver_ID = "20250909/1"
open_date = 2025-09-09 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-09-15 01:00:00
hard_deadline = 2025-09-22 01:00:00

[tasks."20250916/1"]
deliver_ID = "20250916/1"
open_date = 2025-09-16 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-09-22 01:00:00
hard_deadline = 2025-09-29 01:00:00

[tasks."20250916/2"]
deliver_ID = "20250916/2"
open_date = 2025-09-16 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-09-22 01:00:00
hard_deadline = 2025-09-29 01:00:00

[tasks."20250916/3"]
deliver_ID = "20250916/3"
open_date = 2025-09-16 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-09-22 01:00:00
hard_deadline = 2025-09-29 01:00:00

[tasks."20250923/1"]
deliver_ID = "20250923/1"
open_date = 2025-09-23 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-09-29 01:00:00
hard_deadline = 2025-10-06 01:00:00

[tasks."20250923/2"]
deliver_ID = "20250923/2"
open_date = 2025-09-23 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-09-29 01:00:00
hard_deadline = 2025-10-06 01:00:00

[tasks."20250923/3"]
deliver_ID = "20250923/3"
open_date = 2025-09-23 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-09-29 01:00:00
hard_deadline = 2025-10-06 01:00:00

[tasks."20250930/1"]
deliver_ID = "20250930/1"
open_date = 2025-09-30 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-10-06 01:00:00
hard_deadline = 2025-10-13 01:00:00

[tasks."20250930/2"]
deliver_ID = "20250930/2"
open_date = 2025-09-30 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-10-06 01:00:00
hard_deadline = 2025-10-13 01:00:00

[tasks."20250930/3"]
deliver_ID = "20250930/3"
open_date = 2025-09-30 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-10-06 01:00:00
hard_deadline = 2025-10-13 01:00:00

[tasks."20251007/1"]
deliver_ID = "20251007/1"
open_date = 2025-10-07 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-10-13 01:00:00
hard_deadline = 2025-10-20 01:00:00

[tasks."20251007/2"]
deliver_ID = "20251007/2"
open_date = 2026-10-07 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2026-10-13 01:00:00
hard_deadline = 2026-10-20 01:00:00

[tasks."20251007/3"]
deliver_ID = "20251007/3"
open_date = 2026-10-07 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2026-10-13 01:00:00
hard_deadline = 2026-10-20 01:00:00

[tasks."20251014/1"]
deliver_ID = "20251014/1"
open_date = 2025-10-14 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-10-20 01:00:00
hard_deadline = 2025-10-27 01:00:00

[tasks."20251014/2"]
deliver_ID = "20251014/2"
open_date = 2025-10-14 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-10-20 01:00:00
hard_deadline = 2025-10-27 01:00:00

[tasks."20251014/3"]
deliver_ID = "20251014/3"
open_date = 2025-10-14 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-10-20 01:00:00
hard_deadline = 2025-10-27 01:00:00

[tasks."20251021/1"]
deliver_ID = "20251021/1"
open_date = 2025-10-21 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-10-27 01:00:00
hard_deadline = 2025-11-03 01:00:00

[tasks."20251021/2"]
deliver_ID = "20251021/2"
open_date = 2025-10-21 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-10-27 01:00:00
hard_deadline = 2025-11-03 01:00:00

[tasks."20251021/3"]
deliver_ID = "20251021/3"
open_date = 2025-10-21 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-10-27 01:00:00
hard_deadline = 2025-11-03 01:00:00

[tasks."20251028/1"]
deliver_ID = "20251028/1"
open_date = 2025-10-28 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-11-03 01:00:00
hard_deadline = 2025-11-10 01:00:00

[tasks."20251028/2"]
deliver_ID = "20251028/2"
open_date = 2025-10-28 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-11-03 01:00:00
hard_deadline = 2025-11-10 01:00:00

[tasks."20251028/3"]
deliver_ID = "20251028/3"
open_date = 2025-10-28 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-11-03 01:00:00
hard_deadline = 2025-11-10 01:00:00

[tasks."20251110/1"]
deliver_ID = "20251110/1"
open_date = 2025-11-10 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-11-16 01:00:00
hard_deadline = 2025-11-23 01:00:00

[tasks."20251110/2"]
deliver_ID = "20251110/2"
open_date = 2025-11-10 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-11-16 01:00:00
hard_deadline = 2025-11-23 01:00:00

[tasks."20251110/3"]
deliver_ID = "20251110/3"
open_date = 2025-11-10 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-11-16 01:00:00
hard_deadline = 2025-11-23 01:00:00

[tasks."20251111/1"]
deliver_ID = "20251111/1"
open_date = 2025-11-11 01:00:00
soft_deadline_delta = "open_date+9d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-11-20 01:00:00
hard_deadline = 2025-11-24 01:00:00

[tasks."20251111/2"]
deliver_ID = "20251111/2"
open_date = 2025-11-11 01:00:00
soft_deadline_delta = "open_date+9d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-11-20 01:00:00
hard_deadline = 2025-11-24 01:00:00

[tasks."20251111/3"]
deliver_ID = "20251111/3"
open_date = 2025-11-11 01:00:00
soft_deadline_delta = "open_date+9d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-11-20 01:00:00
hard_deadline = 2025-11-24 01:00:00

[tasks."20251118/1"]
deliver_ID = "20251118/1"
open_date = 2025-11-18 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-11-24 01:00:00
hard_deadline = 2025-12-01 01:00:00

[tasks."20251118/2"]
deliver_ID = "20251118/2"
open_date = 2025-11-18 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-11-24 01:00:00
hard_deadline = 2025-12-01 01:00:00

[tasks."20251118/3"]
soft_deadline_delta = "open_date+9d"
open_date = 2025-11-18 01:00:00
deliver_ID = "20251118/3"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-11-27 01:00:00
hard_deadline = 2025-12-01 01:00:00

[tasks."20251125/1"]
deliver_ID = "20251125/1"
open_date = 2025-11-25 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-12-01 01:00:00
hard_deadline = 2025-12-08 01:00:00

[tasks."20251125/2"]
deliver_ID = "20251125/2"
open_date = 2025-11-25 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-12-01 01:00:00
hard_deadline = 2025-12-08 01:00:00

[tasks."20251202/1"]
deliver_ID = "20251202/1"
open_date = 2025-12-02 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-12-08 01:00:00
hard_deadline = 2025-12-15 01:00:00

[tasks."20251202/2"]
deliver_ID = "20251202/2"
open_date = 2025-12-02 01:00:00
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2025-12-08 01:00:00
hard_deadline = 2025-12-15 01:00:00

[make]
screenreplay = false
deadline_gap = 03:00:00

[check]
directory = "hworker_check"
user_checks = true

[formalization]
prog_name = "prog.py"
remote_name = "remote"
check_name = "check"
runtime_suffix = [
    "in",
    "out",
]
validate_suffix = "py"
validator_name = "validator"
version_validator_name = "version_validator"
no_merge = [
    "checks",
]

[publish]
host = "0.0.0.0"
port = "8080"
course_name = "My prac"
secret_cookie = "kapibara"
static_folder = "static"
url_prefix = ""
SECRET_KEY = "8556aa9cfdd8c8e0884d1b2568985789372281093f338caf5cc145fdb9e5f7b5"

[score]
score_directory = "scores"

[depot]
database_path = "data.db"
